/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Arquivo;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joaovitor
 */
public class Input_file extends javax.swing.JFrame {

    /**
     * Creates new form Input_file
     */
    public Input_file() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_ver = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        visualizacao_previa = new javax.swing.JTextPane();
        bt_ok = new javax.swing.JButton();
        bt_preview = new javax.swing.JButton();
        ff_par = new javax.swing.JTabbedPane();
        Estrutura = new javax.swing.JPanel();
        box = new javax.swing.JPanel();
        box_x = new javax.swing.JPanel();
        cord_x = new javax.swing.JSpinner();
        box_y = new javax.swing.JPanel();
        cord_y = new javax.swing.JSpinner();
        box_z = new javax.swing.JPanel();
        cord_z = new javax.swing.JSpinner();
        molec = new javax.swing.JPanel();
        txt_molec = new javax.swing.JTextField();
        quantidade_de_molec = new javax.swing.JPanel();
        txt_quantidade_molec = new javax.swing.JTextField();
        atomos_por_molecula = new javax.swing.JPanel();
        txt_atomos_p_molec = new javax.swing.JTextField();
        reuse = new javax.swing.JPanel();
        sp_reuse = new javax.swing.JSpinner();
        md_parameters = new javax.swing.JPanel();
        p_nhist = new javax.swing.JPanel();
        txt_nhist = new javax.swing.JTextField();
        p_preext = new javax.swing.JPanel();
        txt_prxt = new javax.swing.JTextField();
        p_text = new javax.swing.JPanel();
        txt_text = new javax.swing.JTextField();
        p_ntrialmax = new javax.swing.JPanel();
        txt_ntrial = new javax.swing.JTextField();
        p_nrelax = new javax.swing.JPanel();
        sp_relax = new javax.swing.JSpinner();
        p_time_setp = new javax.swing.JPanel();
        txt_timestep = new javax.swing.JTextField();
        p_ensemble = new javax.swing.JPanel();
        txt_es1 = new javax.swing.JTextField();
        txt_es2 = new javax.swing.JTextField();
        txt_es3 = new javax.swing.JTextField();
        p_ensemble1 = new javax.swing.JPanel();
        txt_rco1 = new javax.swing.JTextField();
        txt_rco2 = new javax.swing.JTextField();
        ff = new javax.swing.JPanel();
        bt_create = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();

        j_ver.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        j_ver.setTitle("Preview");
        j_ver.setMinimumSize(new java.awt.Dimension(460, 440));

        visualizacao_previa.setEditable(false);
        visualizacao_previa.setBackground(new java.awt.Color(255, 230, 0));
        visualizacao_previa.setFont(new java.awt.Font("Abyssinica SIL", 0, 15)); // NOI18N
        visualizacao_previa.setForeground(new java.awt.Color(5, 0, 0));
        jScrollPane1.setViewportView(visualizacao_previa);

        bt_ok.setText("Ok");
        bt_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j_verLayout = new javax.swing.GroupLayout(j_ver.getContentPane());
        j_ver.getContentPane().setLayout(j_verLayout);
        j_verLayout.setHorizontalGroup(
            j_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_verLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_verLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        j_verLayout.setVerticalGroup(
            j_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_verLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_ok)
                .addGap(52, 52, 52))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gimols");

        bt_preview.setText("Preview");
        bt_preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_previewActionPerformed(evt);
            }
        });

        Estrutura.setBorder(javax.swing.BorderFactory.createTitledBorder("Structure variables"));

        box.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Box"));

        box_x.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "X:"));

        cord_x.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout box_xLayout = new javax.swing.GroupLayout(box_x);
        box_x.setLayout(box_xLayout);
        box_xLayout.setHorizontalGroup(
            box_xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cord_x, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        box_xLayout.setVerticalGroup(
            box_xLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cord_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        box_y.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Y:"));

        cord_y.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout box_yLayout = new javax.swing.GroupLayout(box_y);
        box_y.setLayout(box_yLayout);
        box_yLayout.setHorizontalGroup(
            box_yLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cord_y, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        box_yLayout.setVerticalGroup(
            box_yLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cord_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        box_z.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Z:"));

        cord_z.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout box_zLayout = new javax.swing.GroupLayout(box_z);
        box_z.setLayout(box_zLayout);
        box_zLayout.setHorizontalGroup(
            box_zLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cord_z, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        box_zLayout.setVerticalGroup(
            box_zLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cord_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout boxLayout = new javax.swing.GroupLayout(box);
        box.setLayout(boxLayout);
        boxLayout.setHorizontalGroup(
            boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxLayout.createSequentialGroup()
                .addComponent(box_x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(box_y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(box_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        boxLayout.setVerticalGroup(
            boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(box_z, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(box_y, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(box_x, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        molec.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Molec"));

        javax.swing.GroupLayout molecLayout = new javax.swing.GroupLayout(molec);
        molec.setLayout(molecLayout);
        molecLayout.setHorizontalGroup(
            molecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_molec)
        );
        molecLayout.setVerticalGroup(
            molecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_molec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        quantidade_de_molec.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Number of molecules"));

        javax.swing.GroupLayout quantidade_de_molecLayout = new javax.swing.GroupLayout(quantidade_de_molec);
        quantidade_de_molec.setLayout(quantidade_de_molecLayout);
        quantidade_de_molecLayout.setHorizontalGroup(
            quantidade_de_molecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_quantidade_molec, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        quantidade_de_molecLayout.setVerticalGroup(
            quantidade_de_molecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_quantidade_molec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        atomos_por_molecula.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Atoms per molecule"));

        javax.swing.GroupLayout atomos_por_moleculaLayout = new javax.swing.GroupLayout(atomos_por_molecula);
        atomos_por_molecula.setLayout(atomos_por_moleculaLayout);
        atomos_por_moleculaLayout.setHorizontalGroup(
            atomos_por_moleculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_atomos_p_molec, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        atomos_por_moleculaLayout.setVerticalGroup(
            atomos_por_moleculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_atomos_p_molec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        reuse.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Reuse"));

        sp_reuse.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout reuseLayout = new javax.swing.GroupLayout(reuse);
        reuse.setLayout(reuseLayout);
        reuseLayout.setHorizontalGroup(
            reuseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_reuse, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        reuseLayout.setVerticalGroup(
            reuseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_reuse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout EstruturaLayout = new javax.swing.GroupLayout(Estrutura);
        Estrutura.setLayout(EstruturaLayout);
        EstruturaLayout.setHorizontalGroup(
            EstruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstruturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EstruturaLayout.createSequentialGroup()
                        .addGroup(EstruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(quantidade_de_molec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(molec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(EstruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atomos_por_molecula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reuse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        EstruturaLayout.setVerticalGroup(
            EstruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstruturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EstruturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EstruturaLayout.createSequentialGroup()
                        .addComponent(molec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quantidade_de_molec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EstruturaLayout.createSequentialGroup()
                        .addComponent(atomos_por_molecula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(reuse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 80, Short.MAX_VALUE))
        );

        ff_par.addTab("Structure", Estrutura);

        md_parameters.setBorder(javax.swing.BorderFactory.createTitledBorder("Molecular dynamics variables"));

        p_nhist.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "N.Hist"));

        javax.swing.GroupLayout p_nhistLayout = new javax.swing.GroupLayout(p_nhist);
        p_nhist.setLayout(p_nhistLayout);
        p_nhistLayout.setHorizontalGroup(
            p_nhistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_nhist, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        p_nhistLayout.setVerticalGroup(
            p_nhistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_nhist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        p_preext.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "PreExt"));

        javax.swing.GroupLayout p_preextLayout = new javax.swing.GroupLayout(p_preext);
        p_preext.setLayout(p_preextLayout);
        p_preextLayout.setHorizontalGroup(
            p_preextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_prxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        p_preextLayout.setVerticalGroup(
            p_preextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_preextLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_prxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_text.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Text"));

        javax.swing.GroupLayout p_textLayout = new javax.swing.GroupLayout(p_text);
        p_text.setLayout(p_textLayout);
        p_textLayout.setHorizontalGroup(
            p_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_text, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        p_textLayout.setVerticalGroup(
            p_textLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_textLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_ntrialmax.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "NTrialMax"));

        javax.swing.GroupLayout p_ntrialmaxLayout = new javax.swing.GroupLayout(p_ntrialmax);
        p_ntrialmax.setLayout(p_ntrialmaxLayout);
        p_ntrialmaxLayout.setHorizontalGroup(
            p_ntrialmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_ntrial, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        p_ntrialmaxLayout.setVerticalGroup(
            p_ntrialmaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_ntrialmaxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_ntrial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_nrelax.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "NRelax"));

        sp_relax.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        javax.swing.GroupLayout p_nrelaxLayout = new javax.swing.GroupLayout(p_nrelax);
        p_nrelax.setLayout(p_nrelaxLayout);
        p_nrelaxLayout.setHorizontalGroup(
            p_nrelaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_relax, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        p_nrelaxLayout.setVerticalGroup(
            p_nrelaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_nrelaxLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sp_relax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_time_setp.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "TimeStep"));

        javax.swing.GroupLayout p_time_setpLayout = new javax.swing.GroupLayout(p_time_setp);
        p_time_setp.setLayout(p_time_setpLayout);
        p_time_setpLayout.setHorizontalGroup(
            p_time_setpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_timestep, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        p_time_setpLayout.setVerticalGroup(
            p_time_setpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_time_setpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_timestep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_ensemble.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Ensemble Npt Berendsen"));

        txt_es1.setToolTipText("");

        javax.swing.GroupLayout p_ensembleLayout = new javax.swing.GroupLayout(p_ensemble);
        p_ensemble.setLayout(p_ensembleLayout);
        p_ensembleLayout.setHorizontalGroup(
            p_ensembleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ensembleLayout.createSequentialGroup()
                .addComponent(txt_es1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_es2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_es3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        p_ensembleLayout.setVerticalGroup(
            p_ensembleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_ensembleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_es1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(p_ensembleLayout.createSequentialGroup()
                .addGroup(p_ensembleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_es2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_es3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        p_ensemble1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "RCutoff"));

        javax.swing.GroupLayout p_ensemble1Layout = new javax.swing.GroupLayout(p_ensemble1);
        p_ensemble1.setLayout(p_ensemble1Layout);
        p_ensemble1Layout.setHorizontalGroup(
            p_ensemble1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ensemble1Layout.createSequentialGroup()
                .addComponent(txt_rco1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_rco2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        p_ensemble1Layout.setVerticalGroup(
            p_ensemble1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_ensemble1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(p_ensemble1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout md_parametersLayout = new javax.swing.GroupLayout(md_parameters);
        md_parameters.setLayout(md_parametersLayout);
        md_parametersLayout.setHorizontalGroup(
            md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_parametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(md_parametersLayout.createSequentialGroup()
                        .addComponent(p_ensemble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p_ensemble1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(md_parametersLayout.createSequentialGroup()
                        .addGroup(md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, md_parametersLayout.createSequentialGroup()
                                .addComponent(p_ntrialmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(p_nrelax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(md_parametersLayout.createSequentialGroup()
                                .addComponent(p_nhist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(p_preext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p_time_setp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        md_parametersLayout.setVerticalGroup(
            md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(md_parametersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(md_parametersLayout.createSequentialGroup()
                        .addGroup(md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(p_nhist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p_preext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(p_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(md_parametersLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(p_ntrialmax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, md_parametersLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p_time_setp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(p_nrelax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(md_parametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p_ensemble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_ensemble1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        ff_par.addTab("Molecular Dynamics", md_parameters);

        javax.swing.GroupLayout ffLayout = new javax.swing.GroupLayout(ff);
        ff.setLayout(ffLayout);
        ffLayout.setHorizontalGroup(
            ffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        ffLayout.setVerticalGroup(
            ffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        ff_par.addTab("Force Field", ff);

        bt_create.setText("Create");
        bt_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_createActionPerformed(evt);
            }
        });

        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_create)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_preview))
                    .addComponent(ff_par))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ff_par)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_preview)
                    .addComponent(bt_create)
                    .addComponent(bt_back))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_previewActionPerformed
        // TODO add your handling code here:
        double cx = (int) cord_x.getValue(), cy = (int) cord_y.getValue(), cz = (int) cord_z.getValue();
        String a = "# Structure variables\n\n&STRUCT\ncell\n";
        if (cx >= 10) {
            a = a+cx + " 0.0  " + "0.0\n";
        }
        if (cx < 10) {
            a = a+cx + "  0.0  " + "0.0\n";
        }
        if (cy >= 10) {
            a = a+"0.0 " + cy + "  0.0\n";
        }
        if (cy < 10) {
            a = a+"0.0  " + cy + "  0.0\n";
        }
        if (cz >= 10) {
            a = a+"0.0  0.0 " + cz+"\n";
        }
        if (cz < 10) {
            a = a+"0.0  0.0  " + cz+"\n";
        }
        //previa estrutura
        a = a+"molecs 1\n"+txt_molec.getText()+" "+txt_quantidade_molec.getText()+" "+txt_atomos_p_molec.getText()+"\n"+"reuse "+sp_reuse.getValue()+"\n&END\n\n# Molecular dynamics variables\n\n";
        //previa md
        a = a+"&MD\nnhist "+txt_nhist.getText()+"\npreext "+txt_prxt.getText()+"\nntrialmax "+txt_ntrial.getText()+"\nnrelax "+sp_relax.getValue()+"\ntimestep "+txt_timestep.getText()+"\nensemble npt berendsen "+txt_es1.getText()+" "+txt_es2.getText()+" "+txt_es3.getText()+"\nrcutoff "+txt_rco1.getText()+" "+txt_rco2.getText()+"\n&END";
        visualizacao_previa.setText(a);
        j_ver.show();
    }//GEN-LAST:event_bt_previewActionPerformed

    private void bt_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_createActionPerformed
        // TODO add your handling code here:
        int cx = (int) cord_x.getValue(), cy = (int) cord_y.getValue(), cz = (int) cord_z.getValue(), reuse = (int) sp_reuse.getValue();
        //caso algum nao preenchido
        if (cx == 0 || cy == 0 || cz == 0 || txt_molec.getText().isEmpty() || txt_quantidade_molec.getText().isEmpty()
                || txt_atomos_p_molec.getText().isEmpty() || txt_nhist.getText().isEmpty() || txt_prxt.getText().isEmpty()
                || txt_text.getText().isEmpty() || txt_ntrial.getText().isEmpty() || txt_timestep.getText().isEmpty()
                || txt_es1.getText().isEmpty() || txt_es2.getText().isEmpty() || txt_es3.getText().isEmpty() || txt_rco1.getText().isEmpty() || txt_rco2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Some information is not supported or has not been completed", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            Arquivo aq = new Arquivo(cx, cy, cz, txt_molec.getText(), txt_quantidade_molec.getText(),txt_atomos_p_molec.getText(), reuse,txt_nhist.getText(),txt_prxt.getText(),txt_text.getText(), txt_ntrial.getText(), (int) sp_relax.getValue(), txt_timestep.getText(), txt_es1.getText(),txt_es2.getText(),txt_es3.getText(),txt_rco1.getText(), txt_rco2.getText());
            aq.criarImput();
        }

    }//GEN-LAST:event_bt_createActionPerformed

    private void bt_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_okActionPerformed
        // TODO add your handling code here:
        j_ver.dispose();
    }//GEN-LAST:event_bt_okActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        // TODO add your handling code here:
        new Menu().show();
        dispose();
    }//GEN-LAST:event_bt_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_file.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_file().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Estrutura;
    private javax.swing.JPanel atomos_por_molecula;
    private javax.swing.JPanel box;
    private javax.swing.JPanel box_x;
    private javax.swing.JPanel box_y;
    private javax.swing.JPanel box_z;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_create;
    private javax.swing.JButton bt_ok;
    private javax.swing.JButton bt_preview;
    private javax.swing.JSpinner cord_x;
    private javax.swing.JSpinner cord_y;
    private javax.swing.JSpinner cord_z;
    private javax.swing.JPanel ff;
    private javax.swing.JTabbedPane ff_par;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFrame j_ver;
    private javax.swing.JPanel md_parameters;
    private javax.swing.JPanel molec;
    private javax.swing.JPanel p_ensemble;
    private javax.swing.JPanel p_ensemble1;
    private javax.swing.JPanel p_nhist;
    private javax.swing.JPanel p_nrelax;
    private javax.swing.JPanel p_ntrialmax;
    private javax.swing.JPanel p_preext;
    private javax.swing.JPanel p_text;
    private javax.swing.JPanel p_text1;
    private javax.swing.JPanel p_text2;
    private javax.swing.JPanel p_text3;
    private javax.swing.JPanel p_time_setp;
    private javax.swing.JPanel quantidade_de_molec;
    private javax.swing.JPanel reuse;
    private javax.swing.JSpinner sp_relax;
    private javax.swing.JSpinner sp_reuse;
    private javax.swing.JTextField txt_atomos_p_molec;
    private javax.swing.JTextField txt_es1;
    private javax.swing.JTextField txt_es2;
    private javax.swing.JTextField txt_es3;
    private javax.swing.JTextField txt_molec;
    private javax.swing.JTextField txt_nhist;
    private javax.swing.JTextField txt_ntrial;
    private javax.swing.JTextField txt_prxt;
    private javax.swing.JTextField txt_quantidade_molec;
    private javax.swing.JTextField txt_rco1;
    private javax.swing.JTextField txt_rco2;
    private javax.swing.JTextField txt_text;
    private javax.swing.JTextField txt_text1;
    private javax.swing.JTextField txt_text2;
    private javax.swing.JTextField txt_text3;
    private javax.swing.JTextField txt_timestep;
    private javax.swing.JTextPane visualizacao_previa;
    // End of variables declaration//GEN-END:variables
}
